# Site settings
title: Planet Jupyter
# email: dev@appanah.org
description: Journey into Data Science
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dev_appanah
github_username:  devappanah

# Build settings
markdown: kramdown
